import { Bangers } from "next/font/google";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import Navabr from "@/components/ui/navbar";
import Providers from "@/components/providers";

// global css for the whole app
import "simplebar-react/dist/simplebar.min.css";
import "react-loading-skeleton/dist/skeleton.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Providers>
        <body
          className={`${(cn("grainy grainy min-h-screen antialiased"), bangers.className)}`}
        >
          <Toaster />
          <Navabr />
          {children}
        </body>
      </Providers>
    </html>
  );
}
