import { Bangers } from "next/font/google";
import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import Navabr from "@/components/ui/navbar";
import Providers from "@/components/providers";

const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Providers>
        <body
          className={`${(cn("grainy grainy min-h-screen antialiased"), bangers.className)}`}
        >
          <Navabr />
          {children}
        </body>
      </Providers>
    </html>
  );
}
